### ISSUE TITLE
minio-mc: Erros de certificado TLS e conexão com o serviço MinIO

### ISSUE THREAD

**Issue by ivanmirandaf** [clairton/unoapi-cloud#104]
### **Descrição do Problema**
O minio-mc parece estar enfrentando problemas relacionados ao certificado TLS e à conexão com o serviço MinIO. Apesar disso, não foram encontrados erros nos logs do Traefik relacionados à geração do certificado. Além disso, o Chatwoot está acessível normalmente via HTTPS, e o certificado Let's Encrypt é exibido corretamente no navegador, com todos os detalhes válidos.
### **Log minio-mc**
```
root@unochat:~# docker compose -f unoapi-cloud/docker-compose.yaml logs -f minio-mc
mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://minio-s3.meudominio.com.br/probe-bsign-mkz3lwuocnwiw4fdepp65gy1j2to1n/?location=": Connection closed by foreign host https://minio-s3.meudominio.com.br/probe-bsign-mkz3lwuocnwiw4fdepp65gy1j2to1n/?location=. Retry again.
mc: <ERROR> Unable to make bucket local/unochat. Put "http://localhost:9000/unochat/": dial tcp [::1]:9000: connect: connection refused
```
### **Comportamento esperado**
 O minio-mc deve se conectar ao serviço MinIO sem problemas, utilizando o certificado TLS válido.

### **Contexto**
Estou utilizando a stack de exemplo do próprio projeto, com apenas alterações nos valores das variáveis de ambiente para adaptar ao ambiente atual.

- docker-compose.yaml

```
version: '3'

x-base: &base
  image: clairton/chatwoot:v3.4.4-uno
  restart: always
  env_file: .env
  links:
    - traefik:${MINIO_DOMAIN}
    - traefik:${UNOAPI_DOMAIN}

services:
  traefik:
    image: traefik:2.4
    restart: always
    env_file: .env
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    command:
      - --api
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.http=true
      - --entrypoints.http.address=:80
      - --entrypoints.https=true
      - --entrypoints.https.address=:443
      - --log=true
      - --log.level=DEBUG
      - --entrypoints.web.http.redirections.entrypoint.to=https
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.myresolver.acme.email=${LETSECRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

  chatwoot-web:
    <<: *base
    depends_on:
      - postgres
      - redis
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    labels:
      - traefik.enable=true
      - traefik.http.services.chatwoot.loadbalancer.server.port=3000
      - traefik.http.routers.chatwoot.rule=Host(`${CHATWOOT_DOMAIN}`)
      - traefik.http.routers.chatwoot.entrypoints=http,https
      - traefik.http.routers.chatwoot.service=chatwoot
      - traefik.http.routers.chatwoot.tls.certresolver=myresolver

  chatwoot-worker:
    <<: *base
    depends_on:
      - postgres
      - redis
      - unoapi
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  chatwoot-migrate:
    <<: *base
    environment:
      POSTGRES_STATEMENT_TIMEOUT: 600s
    depends_on:
      - postgres
      - redis
    restart: 'no'
    command:  ['bundle', 'exec', 'rails', 'db:chatwoot_prepare']

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    restart: always
    env_file: .env

  postgres:
    image: postgres:16.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    restart: always

  unoapi:
    image: clairton/unoapi-cloud:v1.12.4
    env_file: .env
    depends_on:
      - redis
      - rabbitmq
      - minio
    entrypoint: yarn cloud
    links:
      - traefik:${MINIO_DOMAIN}
      - traefik:${UNOAPI_DOMAIN}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.unoapi.loadbalancer.server.port=9876
      - traefik.http.routers.unoapi.rule=Host(`${UNOAPI_DOMAIN}`)
      - traefik.http.routers.unoapi.entrypoints=http,https
      - traefik.http.routers.unoapi.service=unoapi
      - traefik.http.routers.unoapi.tls.certresolver=myresolver

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always
    env_file: .env
  
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio:/data
    restart: always
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)
      - traefik.http.routers.minio.entrypoints=http,https
      - traefik.http.routers.minio.service=minio
      - traefik.http.routers.minio.tls.certresolver=myresolver

  minio-mc:
    image: quay.io/minio/mc:latest
    env_file: .env
    restart: 'no'
    links:
      - traefik:${MINIO_DOMAIN}
      - traefik:${UNOAPI_DOMAIN}
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local $MINIO_URL $STORAGE_ACCESS_KEY_ID $STORAGE_SECRET_ACCESS_KEY;
      /usr/bin/mc mb local/$STORAGE_BUCKET_NAME;
      "

volumes:
  redis:
  postgres:
  minio:
  rabbitmq:
  letsencrypt:
```

- .env

```
# ------------------ atualizar esses obrigatoriamente inicio ---------------------#
CHATWOOT_DOMAIN=chat.meudominio.com.br
MINIO_DOMAIN=minio-s3.meudominio.com.br
UNOAPI_DOMAIN=unoapi.meudominio.com.br
LETSECRYPT_EMAIL=contato@meudominio.com.br
STORAGE_SECRET_ACCESS_KEY=qBh4B5oMLLLrHEeRLct67c9a7723fb3d
UNOAPI_AUTH_TOKEN=oa2nAq5ob5a3osSFpUXF2VM8

# esse vai conseguir atualizar somente depois de criar o usuario
WEBHOOK_TOKEN=oa2nAq5ob5a3osSFpUXF2VM8
# ------------------ atualizar esses obrigatoriamente final ---------------------#

HTTP_PROTOCOL=https

# url
CHATWOOT_URL=$HTTP_PROTOCOL://$CHATWOOT_DOMAIN
MINIO_URL=$HTTP_PROTOCOL://$MINIO_DOMAIN

# minio
ACTIVE_STORAGE_SERVICE=s3_compatible
STORAGE_ACCESS_KEY_ID=unochat_key
STORAGE_BUCKET_NAME=unochat
STORAGE_ENDPOINT=$MINIO_URL
STORAGE_FORCE_PATH_STYLE=true
STORAGE_REGION=us-east-1
MINIO_ROOT_USER=$STORAGE_ACCESS_KEY_ID
MINIO_ROOT_PASSWORD=$STORAGE_SECRET_ACCESS_KEY
MINIO_SERVER_URL=$MINIO_URL

#postgres
POSTGRES_PASSWORD=qv167c9a78bcff8d
POSTGRES_USER=unochat
POSTGRES_DB=chatwoot

#rabbitmq
RABBITMQ_DEFAULT_USER=unochat
RABBITMQ_DEFAULT_PASS=FET67c9a7992fbd8

# chatwoot
FRONTEND_URL=$CHATWOOT_URL
SECRET_KEY_BASE=O1JiqMF3DQk2oicjkmfFxZM2s4qGWGMQ3dnVcC8SD5YDePAkjK967c9a7b8987a5
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
REDIS_URL=redis://redis:6379
INSTALLATION_ENV=docker
NODE_ENV=production
RAILS_ENV=production

#unoapi
WEBHOOK_HEADER=unoapi
WEBHOOK_URL=$CHATWOOT_URL/webhooks/whatsapp
AMQP_URL=amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@rabbitmq:5672
BASE_URL=$HTTP_PROTOCOL://$UNOAPI_DOMAIN
LOG_LEVEL=debug
UNO_LOG_LEVEL=debug

# compose project name
COMPOSE_PROJECT_NAME=unochat
```
